ZDK.define('lang.verify',function(require,exports){var lang={required:'该字段为必选项！',min:'该字段最小长度不能低于{min}位！',max:'该字段最大长度不能高于{max}位！',pattern:'该字段不满足模式条件！','int':'请输入正确的整型！',email:'请输入正确的邮件(email)地址！',url:'请输入正确的URL地址！',date:'请输入正确的日期格式!',time:'请输入正确的时间格式!',qq:'请输入正确的QQ号码',tel:'请输入正确的手机号码',phone:'请输入正确的座机号码',contact:'不能包含联系方式！'};exports.translation=function(key){return lang[key]||'';};});;ZDK.define('module.wtaid',function(require,exports){var WTaid=exports.wtaid=function(){},SCRIPT=/<script\s*type=['"]?([^'"]+)['"]?>([\w\W]+?)<\/script>/igm,CACHE={};WTaid.callee=function(self,callee,options){if(!options.id){options.id=(typeof options.content=='string'&&options.content)?ZDK.hash(options.content):ZDK.uuid();}
var youCan=options.target;if(!youCan){opcache();}else if(youCan.hasClass("childs")){var _flag=youCan.attr("flag")
if(_flag>0&&options.cache){return opcache();}else{youCan.attr("flag",++_flag);}}
if(!(self instanceof callee)){return new callee(options);}
function opcache(){if(options.cache==undefined||options.cache){if((wtaid=CACHE[options.id])){$.extend(wtaid.opche,options);wtaid.trigger('cache',{target:wtaid});wtaid.reset&&wtaid.reset();return wtaid.show();}}}
self.entry(options);};WTaid.prototype={entry:function(options){var opche=this.opche=$.extend({target:null,title:'弹出窗口',id:null,content:'',iframe:false,cache:true,allowClose:true,escClose:false,cancel:true,ok:true,height:'auto',width:560,onInited:null,zIndex:100,mask:true,theme:''},options),self=this,wtaid;opche.cache&&(CACHE[options.id]=self);!($.browser.msie&&($.browser.version=="6.0")&&!$.support.style)&&(this.opche.hasIframe=false);((self.pageurl=false)||(typeof opche.content=='string'))&&(opche.content.match(/^([^<>]+|[a-z\/.\?%@&=]+)$/i))&&(self.pageurl=opche.content);opche.iframe=opche.iframe&&self.pageurl;opche.escClose=opche.escClose&&opche.allowClose;if(self.pageurl){self.jsonp=false;if(isJSONPRequest()){self.jsonp=true;}}
self.init(this);function isJSONPRequest(){return self.pageurl.indexOf(location.host)==-1||self.pageurl.indexOf('jsonpcallback')!=-1;}},init:function(self,tc){self.create();self.bindTarget(self.Window);if(!self.pageurl){self.Body.html('').append(self.opche.content);}else{if(self.opche.iframe){return self.bindIframe();}
self.on('click:wtaid-reasyn',function(){self.Body.html('<p class="ui-initwait">正在重新连</a>');self.pageurl+=(self.pageurl.indexOf('?')>-1?'&':'?')+'t='+ZDK.uuid();self.asyn();});self.asyn();}
self.show();self._inited(self);self.opche.onInited&&self.opche.onInited(self);self.Window.css('z-index',self.opche.zIndex);},_inited:function(self,data,tc){(tc=self.opche.width)&&self.resetWidth(tc);if((tc=self.opche.height)&&tc!='auto'){self.resetHeight(tc);}
self.inited&&self.inited();self.bind&&self.bind();self.trigger('inited',$.extend({target:data||null}));self.reset&&self.reset();self.ready=true;self.opche.isWindow||self.Window.mousedown(function(e){e.stopPropagation();});self.opche.onContentLoaded&&self.opche.onContentLoaded(self);},asyn:function(){var self=this,asynconfig={type:'post',url:self.pageurl,dataType:self.jsonp?'jsonp':'html',timeout:30000,error:function(icon,status,text){self.trigger('asynerror',{status:status});if(status=='timeout'){text='服务器连接超时';icon='ui-warning';}else{text='服务器连接错误';icon='ui-error';}
self.Body.html('<p class="ui-warning">'+text+',请<a href="javascript:;" action-type="wtaid-reasyn">重试</a>!</p>');return false;},success:function(text){var html=typeof text=='string'?text:text.msg||text.html||text.data||'',script=[];if(!html){return self.trigger('asynerror',{status:'error'})}
if(html.indexOf('{')===0){var json=(new Function('return '+html))();if(json.state==1){html=json.msg;}else{self.hide();return ZDK.Tips(json.msg,2000,"warning");}}
self.Body[0].innerHTML=html.replace(SCRIPT,function(_,$0,$1){if($0!=='text/tpl'){$1=operationReplace($1);script.push($1);return'';}
return $1;});self.script(script.length?script.join(';'):'');self._inited(self);}};function operationReplace(str){var stmt=" if(window.healthBtnClicked) {\
        var paywin = ZDK.module.window({\
         title: '完成支付',\
         content: '',\
         cache: false,\
         width: 550,\
         cancel:'支付失败',\
         ok: '支付成功',\
         onInited: function(win) {\
          win.resetBody('是否支付成功?');\
         }\
        });\
        paywin.on('onok',function(){\
         $(window).trigger('payok');\
        });\
        window.open(json.msg);\
       } else {\
        window.location.href = json.msg;\
       }";str=str.replace(/window\.location\.href\s?=\s?json\.msg;/,stmt);stmt=" if(window.healthBtnClicked) {\
        $(window).trigger('operationok');\
       }\
       $('.task_content').html(json.msg.content);\
       ";str=str.replace(/\$\('\.task_content'\)\.html\(json\.msg\.content\);/,stmt);stmt=" if(window.healthBtnClicked) {\
        $(window).trigger('operationok');\
       }\
       $('#invite-num').html('('+json.num+')');\
       ";str=str.replace(/\$\('#invite-num'\)\.html\('\('\+json\.num\+'\)'\);/,stmt);return str;}
self.show();if(self.jsonp){asynconfig['type']='get';if(self.pageurl.indexOf('jsonpcallback')<=0){asynconfig['url']=self.pageurl+(self.pageurl.indexOf('?')>-1?'&':'?')+'jsonpcallback=?';}else{asynconfig['url']=self.pageurl;}}
if(self.opche.contentType&&self.opche.contentType=='img'){$('<img style="padding:10px"/>').on('load',function(e){if(self.opche.maxWidth){$(this).css('maxWidth',self.opche.maxWidth);}
if(self.opche.maxHeight){$(this).css('maxHeight',self.opche.maxHeight);}
self.Body.empty().append($(this));var ie6=/MSIE 6/i.test(navigator.userAgent);if(ie6){if(self.opche.maxWidth){if(this.width>self.opche.maxWidth){$(this).css('width',self.opche.maxWidth);}}}
self.resetWidth($(this).width()+22);self._inited(self);}).on('error',function(e){self.trigger('asynerror',{status:'error'});var text='服务器连接错误',icon='ui-error';return false;}).attr('src',self.pageurl);}else{$.ajax(asynconfig);}},script:function(script){if(script){window.console&&console.log(script);try{(new Function(script)).call(this)}catch(e){throw new Error("WTaid asyn script error!");}}},show:function(){this.isshow=true;if(false!==this.trigger('showbefore',{target:this})){this.Window.show();}
this.trigger('onshow',{target:this});this.resetPosition&&this.resetPosition();var self=this;setTimeout(function(){self.thide&&$(document).bind('mousedown',{self:self},self.thide);},0);self.opche.mask&&ZDK.mask();},hide:function(){if(this.target&&this.target.attr("act-type")=="thinks")this.target.parents(".user-red").removeAttr("style");if(this.isshow){this.isshow=false;if(false!==this.trigger('hidebefore',{target:this})){this.Window.hide();}
this.trigger('hide',{trigger:this});this.thide&&$(document).unbind('mousedown',this.thide);this.opche.mask&&ZDK.mask(true);!this.opche.cache&&this.Window.remove();}},resetHeight:function(height){if(height){this.Body.css('height',height);this.trigger('resetHeight',{height:height,target:this});this.resetPosition&&this.resetPosition();}},getHeight:function(){return this.Body.height();},resetWidth:function(width){if(width){this.opche.width=width;this.Window.css('width',width);this.trigger('resetWidth',{width:width,targer:this});}},getWidth:function(){return this.Window.width();},bindIframe:function(){var self=this,pageurl=self.pageurl,opche=self.opche;self.Iframe=$('<iframe style="display:none;width:100%;border:none;" frameborder="0" scrolling="no" src="'+pageurl+'"  ></iframe>');self.Iframe.bind('load',function(tc){self.Iframe.show();self.Iframe.css('height',opche.height!=='auto'?opche.height||350:350);self.Body.html('').append(self.Iframe);self.trigger('iframeonload',{iframe:self.Iframe});self.ready=true;self.bind&&self.bind();(tc=self.opche.width)&&self.resetWidth(tc);if((tc=self.opche.height)&&tc!='auto'){self.resetHeight(tc);}
self._inited(self);});return $(document.body).append(self.Iframe);}};return ZDK.procopy(WTaid,ZDK.EventDelegate);});;ZDK.define('module.poptip',function(require,exports){var WTaid=require('module.wtaid').wtaid;var PopTip=exports.poptip=function(options){options.mask=false;return WTaid.callee(this,arguments.callee,options);};PopTip.prototype={create:function(pageurl){PopTip.create(this,pageurl);},bind:function(){var self=this;self.target=$(this.opche.target);},thide:function(e){var self=e.data.self;var target=e.target;if(target&&target.nodeName&&target.nodeName.toUpperCase()=="WEBDATEDAYITEM"){return false;}
if(typeof self.opche.autoclose!='undefined'&&self.opche.autoclose==false){return;}
if(1===e.which){self.hide();}},reset:function(){var self=this,focetop,offset=self.target.offset(),ocss={},width=self.target.outerWidth(true),height=self.target.outerHeight(),WWidth=self.Window.outerWidth(),WHeight=self.Window.outerHeight(),Width=$(window).width(),Height=$(window).height();ocss['left']=offset.left;ocss['top']=offset.top+height+15;if(self.opche.autoreset){self.Window[(focetop=(offset.top<WHeight+$(document.body).scrollTop()+30))?'removeClass':'addClass']('ui-poptip-reverse');}
if(self.opche.right||Width-ocss['left']<WWidth){ocss['left']=offset.left+width-WWidth;self.Arrow.css({left:'auto',right:self.opche.arrowOffset||7});}else{self.Arrow.css({left:7,right:'auto'});}
if(self.opche.right&&ocss['left']<10){ocss['left']=offset.left;self.Arrow.css({left:7,right:'auto'});}
if(!focetop&&self.opche.bottom){ocss['top']=offset.top-15-WHeight;}
this.Window.css({top:ocss['top']+(this.opche.offTop||0),left:ocss['left']+(this.opche.offLeft||0)});this.show();},resetBody:function(body){this.Body.html(body);},resetWidth:function(width){this.Window.css({width:width});}};PopTip.create=function(self,pageurl){var opche=self.opche,ctml;if(opche.bottom){opche.theme+=' ui-poptip-reverse';}
ctml=self.opche.hasIframe?'<div class="ui-poptip-wrapper clearfix">':'';self.opche.hasIframe&&(ctml+='<iframe scrolling="no" class="ui-window-bgd" '+(opche.height&&opche.height!='auto'?'style="height:'+opche.height+'px"':'')+'></iframe>');ctml+='<div class="ui-poptip '+opche.theme+'" style="display:;"><div class="ui-poptip-arrow"><i></i></div><div class="ui-poptip-body"><p class="ui-initwait"> 正在加载中...</p></div></div>';self.opche.hasIframe&&(ctml+='</div>');self.Window=$(ctml).appendTo(document.body);self.Body=self.Window.find('.ui-poptip-body');self.Arrow=self.Window.find('.ui-poptip-arrow');if(opche.right){self.Arrow.css({left:'auto',right:20});}};return ZDK.procopy(PopTip,WTaid);});;ZDK.define('module.window',function(require,exports){var WTaid=require('module.wtaid').wtaid;var Window=exports.window=function(options){options.zIndex=options.zIndex||190;options.isWindow=true;return WTaid.callee(this,arguments.callee,options);};Window.prototype={create:function(){Window.create(this);},bind:function(){var self=this;if(self.opche.escClose){$(document).bind('keyup',function(e){if(e.which==27){self.hide();}});}},reset:function(){this.resetPosition();this.show();if(this.opche.hasIframe){this.Window.find('iframe.ui-window-bgd').css({height:this.Window.height()})}},resetPosition:function(){var width=this.Window.width();var height=this.Window.height();var scroll=$(document).scrollTop();this.Window.css({'margin-left':-width/2,'margin-top':-height/2+scroll});},resetTheme:function(className){this.Window.addClass(className);},resetTitle:function(title){this.Title.html(title);},setTitle:function(title){this.Title.html(title);return this;},setContentNode:function(node){this.Body.empty().append(node);this.resetPosition();return this;},resetBody:function(body){this.Body.html(body);},hideClose:function(){self.Close.hide();},resetFooter:function(footer){this.Footer.show();this.Footer.html(footer);},resetOkButton:function(footer){this.Footer.show();this.Footer.find(".ui-window-ok").html("<i></i>"+footer);},resetCancelButton:function(footer){this.Footer.show();this.Footer.find(".ui-window-cancel").html("<i></i>"+footer);},ok:function(){if(this.Footer.find(".ui-window-ok").attr("disabled")=="disabled"){return false;}
if(false!=this.trigger('onok')){this.hide();}},cancel:function(){if(false!=this.trigger('oncancel')){this.hide();}}};Window.create=function(self){var opche=self.opche,ctml;ctml=['<div class="ui-window '+opche.theme+'">'];self.opche.hasIframe&&ctml.push('<iframe scrolling="no" class="ui-window-bgd" '+(opche.height&&opche.height!='auto'?'style="height:'+opche.height+'px"':'')+'></iframe>');ctml.push('<div class="ui-window-header">');ctml.push('<a href="javascript:;" class="ui-window-close" action-type="window-close" '+(!opche.allowClose?'style="display:none;"':'')+'>×</a>');ctml.push('<h3>'+opche.title+'</h3></div><div class="ui-window-body"><p class="ui-initwait"> 正在加载中...</p></div>');if(opche.ok||opche.cancel){var toolbar='<div class="ui-window-footer">';if(opche.footer){toolbar+=opche.footer;}else{if(opche.cancel){toolbar+='<a href="javascript:void(0);" action-type="window-cancel" class="ui-window-cancel butn small-butn"><i></i>'
+(typeof opche.cancel=='string'?opche.cancel:'取消')+'</a>';}
if(opche.ok){toolbar+='<a href="javascript:void(0);" action-type="window-ok" class="ui-window-ok butn small-butn small-butn-orange"><i></i>'
+(typeof opche.ok=='string'?opche.ok:'确定')+'</a>';}}
ctml.push(toolbar+'</div>');}else{ctml.push('<div class="ui-window-footer" style="display:none;"></div>');}
ctml.push('</div>');self.Window=$(ctml.join('')).appendTo(document.body);self.Header=self.Window.find('.ui-window-header');self.Title=self.Header.find('h3');self.Body=self.Window.find('.ui-window-body');self.Footer=self.Window.find('.ui-window-footer');self.Close=self.Window.find('.ui-window-close');if(toolbar){self.Ok=self.Footer.find('.ui-window-ok');self.Cancel=self.Footer.find('.ui-window-cancel');}
self.on('click:window-cancel',function(){self.cancel();}).on('click:window-ok',function(){self.ok();}).on('click:window-close',function(){self.hide();});};try{return ZDK.procopy(Window,WTaid);}finally{Window.Tips=function(title,content,timeout,icon,callback,errback,btnText){var win=Window.one=Window({title:title,content:(icon?'<div class="'+icon+'">'+content+'</div>':content),id:'winalert'+ZDK.uuid(),width:430,mask:true,cache:false,zIndex:9000,close:false,hasIframe:true,cancel:typeof(errback)=="string"?errback:errback&&true,ok:btnText||true}),timer;if(timeout){timer&&clearTimeout(timer);timer=setTimeout(function(){win.hide();},timeout);}
callback&&win.on('onok',function(){return callback();})
errback&&win.on('oncancel',function(){typeof(errback)=="string"?win.hide():errback();});return win;};ZDK.Alert=function(title,content,timeout,callback,errback,btnText){Window.Tips(title,content,timeout==undefined?4000:timeout,'ui-warning',callback,errback,btnText);};ZDK.Error=function(title,content,timeout,callback,errback,btnText){Window.Tips(title,content,timeout==undefined?4000:timeout,'ui-error',callback,errback,btnText);};ZDK.Success=function(title,content,timeout,callback,errback,btnText){Window.Tips(title,content,timeout==undefined?4000:timeout,'ui-success',callback,errback,btnText);};ZDK.Load=function(options){var opt=options?options:{};var title=opt.title?opt.title:"系统提示";var url=opt.url?opt.url:"";var dataType=opt.dataType?opt.dataType:"html";var callback=opt.callback?opt.callback:false;var errback=opt.errback?opt.errback:false;var loadback=opt.loadback?opt.loadback:false;var width=opt.width?opt.width:430;var ok=opt.ok?opt.ok:false;var cancel=opt.cancel?opt.cancel:false;var zIndex=opt.zIndex?opt.zIndex:9000;var json;var content;$.ajax({url:url,type:opt.type||"get",dataType:dataType,success:function(data){json=data;content=dataType?'<div>'+data.msg+'</div>':data;var win=Window.one=Window({title:title,content:dataType=="html"?data:content,id:'winalert'+ZDK.uuid(),width:width,mask:true,cache:false,zIndex:zIndex,close:false,hasIframe:true,ok:ok,cancel:cancel}),timer;callback&&win.on('onok',function(){callback(win,json);return false});errback&&win.on('oncancel',function(){errback();});loadback&&loadback(win);},error:function(jqXHR,textStatus,errorThrown){content="加载失败，请刷新页面后重试...";}});};}});;ZDK.define('module.verify',function(require,exports){var Lang=require('lang.verify').translation;require('module.poptip');require('module.window');var Verify=exports.verify=function(options){if(!(this instanceof arguments.callee)){return new arguments.callee(options);}
this.entry(options);},regForm=/form/i;Verify.prototype={entry:function(options){this.opche=$.extend({target:null,button:null,item:'.ui-form-item',focusClass:'ui-form-focus',successClass:'ui-form-success',errorClass:'ui-form-error',hoverClass:'ui-form-hover',asynClass:'ui-form-asyn',warningClass:'ui-form-warning',oninited:null,holderLeft:5,holderTop:5,alertType:true},options);this.target=$(this.opche.target);this.button=$(this.opche.button);if(this.target.length==0){return;}
if(!regForm.test(this.target[0].nodeName)){throw new Error("The target must is a form element!");}
for(var data="focus,hover,error,success,asyn,warning".split(','),len=data.length-1,key;len>=0;len--){this['i'+(key=data[len])]=(typeof this.opche[key+='Class']=='string')?this.opche[key].replace('.',''):false;}
this.asyning=false;this.asynCache={};this.asynQueue=[];this.asynResult={};this.asynError={};this.asynSuccess={};this.result={};this.errorTips=[];this.bind();this.opche.oninited&&this.opche.oninited(this);},forceSubmit:function(){this.foSubmit=true;this.target.submit();this.foSubmit=false;},bind:function(){var self=this,tabindex=1;this.target.unbind('submit');this.button.unbind('click').bind('click',function(){self.target.submit();return false;});this.target.submit(function(){if(true===self.submit()){if(self.foSubmit||false!==self.trigger('submitBefore')){return true;}}
return false;});(this.items=this.target.find(this.opche.item)).each(function(i,item){var item=$(item),input=item.find(':input').not('[type=hidden]')||item.find(':textarea'),name=input.attr('name');item.attr('data-index',i);self.bindItem(input,item,name);input.attr('tabIndex',1+i);});this.trigger('bind',{verify:this});},bindItem:function(input,item,name){var self=this,asynURI=Verify.fn.ajaxurl(item),jsonp=asynURI.indexOf('http')>-1,autoFocus=item.attr('autofocus'),placeHolder=item.attr('placeholder'),focusTips=item.attr('focustips');self.trigger('bindItem',{input:input,item:item,name:name});input.focus(function(){self.ifocus&&self.changeState(input,item,'focus');focusTips&&Verify.fn.focustips(input,item,focusTips,name,true);self.trigger('itemfocus',{input:input,item:item});}).blur(function(){if(!item.attr('noblur')){if(self.checkItem(input,item,name)&&asynURI){self.asyn(input,item,asynURI,name,jsonp);}
self.ifocus&&self.changeState(input,item,'focus',true);focusTips&&Verify.fn.focustips(input,item,name);self.trigger('itemblur',{input:input,item:item});}});if(self.ihover){item.hover(function(){self.changeState(input,item,'hover');},function(){self.changeState(input,item,'hover',true);});}
placeHolder&&Verify.fn.placeholder(input,item,placeHolder,self);autoFocus&&　Verify.fn.autofocus(item);},asyn:function(input,item,asyn,name,jsonp,force){var self=this,val,Data=name+'='+(val=input.val()),param;var key=ZDK.hash(asyn);if(!force&&(self.asynCache[key+val]||self.asynCache[key])){}
if(!force&&self.asyning){return(self.asynCache[key]=true)&&　self.asynQueue.push([input,item,asyn,name,jsonp]);}
self.trigger('asyning',{input:input,item:item,asyn:asyn,jsonp:jsonp});self.iasyn&&self.changeState(input,item,'asyning')(input,item,'success',true,self);(param=Verify.fn.parameter(item))&&(Data+='&'+param);if((self.asyning=true)&&jsonp){$.ajax({url:asyn,dataType:'jsonp',jsonp:"jsonpcallback",data:Data,success:function(json){self.asynCallback(json,input,item,asyn,name,val);}});}else{$.ajax({url:asyn,dataType:'html',data:Data,type:'post',success:function(json){json=(new Function('return '+json))();self.asynCallback(json,input,item,asyn,name,val);},error:function(){}});}},asynCallback:function(json,input,item,asyn,name,val){var self=this,pop;(pop=self.asynQueue.pop())&&pop.push(true)?self.asyn.apply(self,pop):(self.asyning=false);var key=ZDK.hash(asyn);self.iasyn&&self.changeState(input,item,'asyning',true);self.asynCache[key]=false;if(json.state==1){self.asynCache[key+val]=true;if(false!=self.trigger('asynSuccess',{json:json,input:input,item:item,name:name,val:val})){self.changeState(input,item,'error',true)(input,item,'success',false,self)(input,item,'asyning',true,self);self.asynResult[name]=true;delete self.asynError[name];self.asynSuccess[name]=json.msg;}}else{self.asynResult[name]=false;self.trigger('asynError',{json:json,input:input,item:item,name:name,val:val});self.asynError[name]=json.msg;self.changeState(input,item,'error');delete self.asynSuccess[name];}},checkItem:function(input,item,name){var val=input.val(),key,res,self=this,type,iret=true;if(input.attr('type')=='checkbox'){val=input.attr('checked');}
self.result[name]=false;for(var p in Verify.property){if((key=item.attr(p))!==undefined){if(key&&(typeof(res=Verify.property[p](key,val,item))=='string')){iret=false;res=item.attr(key+'tips')||res;break;}}}
if(iret&&!val){return true;}
if(iret&&(type=item.attr('type'))&&(type in Verify.type)){if(val&&!Verify.type[type](val,item)){iret=false;res=Lang(type);}}
if((type=item.attr('notype'))&&val){var notype={email:function(val){return /[a-zA-Z0-9_+.-]+\@([a-zA-Z0-9-]+\.)+[a-zA-Z0-9]{2,4}$/.test(val);},qq:function(val){return /[0-9]{5,10}$/.test(val);},tel:function(val){return /1[34586]\d{9}$/.test(val);},phone:function(val){return /(?:\d{3,4})\d{6-8}$/.test(val);}};if(type=="contact"){if(notype["phone"](val,item)||notype["tel"](val,item)||notype["email"](val,item)||notype["qq"](val,item)){iret=false;res=Lang(type);}}else if(type==Verify.type){if(notype[type](val,item)){iret=false;res=Lang(type);}}}
if(self.isubmit&&false===self.asynResult[name]){res=self.asynError[name];iret=false;}
res=!iret?res:self.asynSuccess[name]||res;if(false==iret){if(!item.attr('noblur')&&this.opche.alertType!="pop"){self.trigger('checkerror',{input:input,item:item,name:name,res:res});self.ierror&&self.changeState(input,item,'error')(input,item,'success',true,self)(input,item,'warning',true,self);try{var hlpeInlie=item.find(".help-inline");if(hlpeInlie.get(0).defText){hlpeInlie.html(hlpeInlie.get(0).defText);}
if(item.attr('notype')){hlpeInlie.html(res);}}catch(e){};}
self.isubmit&&this.opche.alertType!="text"&&Verify.fn.errortips&&Verify.fn.errortips(input,item,self.errorTips.push(res)&&res,name,false,this);return iret;}else{if(false!==self.trigger('checksuccess',{input:input,item:item,name:name,res:res})){if(!item.attr('noblur')&&this.opche.alertType!="pop"){self.isuccess&&self.changeState(input,item,'success');self.changeState(input,item,'error',true);try{var hlpeInlie=item.find(".help-inline");if(!hlpeInlie.get(0).defText)hlpeInlie.get(0).defText=hlpeInlie.html();hlpeInlie.html("");}catch(e){};}}else{return false;}}
return self.result[name]=true;},changeState:function(input,item,state,isrm,self){var chstate=[],stateClass='',asyn;if(typeof isrm!=='boolean'){self=isrm;isrm=false;}
self=self||this;if(isrm&&asyn){return arguments.callee;}
switch(state){case'success':stateClass=asyn?self.ierror:self.isuccess;break;case'error':stateClass=self.ierror;break;case'warning':stateClass=self.iwarning;break;case'asyning':stateClass=self.iasyn;break;case'focus':stateClass=self.ifocus;break;default:return arguments.callee;}
if(stateClass){item[isrm?'removeClass':'addClass'](stateClass);input[isrm?'removeClass':'addClass'](stateClass);}
return arguments.callee;},submit:function(){var length=this.items.length,sucidx=0,self=this;this.errorTips=[];this.isubmit=true;if(false!==self.trigger('scheckBefore',{target:self})){self.items.each(function(i,item){var item=$(item);var input=item.find(':input').not('[type=hidden]');if(self.checkItem(input,item,input.attr('name'))){++sucidx;}else{return false;}});}
this.isubmit=false;return length===sucidx;}};Verify.tips=function(){var tips,ctips,timer;var hide=function(tips){timer&&clearTimeout(timer);return timer=setTimeout(function(){tips&&tips.hide();timer=null;},3000);};return function(input,item,title,name,focus,verify){var callee=arguments.callee;callee[ctips]&&callee[ctips].hide();if(arguments.length==3){return callee[name]&&callee[name].hide();}
tips=ZDK.module.poptip({target:input,content:'<p class="ui-warning-min">'+title+'</p>',align:true,theme:'ui-verify-tips',width:50+title.length*16,height:32,id:'verify-tips-'+name,rebody:true,zIndex:10000,datatitle:title,hasIframe:true,datafocus:focus});verify&&verify.trigger('ontips',{title:title,input:input,item:item});if(!callee[ctips=name]){tips.on('cache',function(data){var tips=data.target;tips.resetWidth(50+tips.opche.datatitle.length*16);tips.resetBody('<p class="ui-warning-min">'+tips.opche.datatitle+'</p>');tips.reset();!tips.opche.datafocus&&hide(tips);});callee[name]=tips;}!focus&&hide(tips)&&input.focus();};}();Verify.type={'int':function(val){return /^[0-9]+$/.test(val);},userid:function(val){return /(^\d{15}$)|(^\d{18}$)|(^\d{17}(\d|X|x)$)/.test(val);},email:function(val){return /^[a-zA-Z0-9_+.-]+\@([a-zA-Z0-9-]+\.)+[a-zA-Z0-9]{2,4}$/.test(val);},url:function(val){return /^http:\/\/[A-Za-z0-9]+\.[A-Za-z0-9]+[\/=\?%\-&_~`@[\]\':+!]*([^<>\"\"])*$/.test(val);},date:function(val,item){var format=(item.attr('dateformat')||'YYYY-MM-DD').toUpperCase();format=format.replace('YYYY','[12][09][0-9][0-9]').replace('YY','[7-9][0-9]').replace('MM','[10][0-9]').replace('M','[10]?[0-9]').replace('DD','[0-3][0-9]').replace('D','[0-3]?[0-9]');try{format=new RegExp('^'+format+'$');}catch(e){throw"DataFormat is error:"+format;}
return format.test(val);},time:function(val){return /^[0-2][0-9]:[0-5][0-9]:[0-5][0-9]$/.test(val);},qq:function(val){return /^[0-9]{5,10}$/.test(val);},tel:function(val){return /^1[34586]\d{9}$/.test(val);},phone:function(val){return /^(?:\d{3,4})\d{6-8}$/.test(val);}};Verify.property={required:function(required,val){return required!==undefined?!!val?true:Lang('required'):true;},min:function(min,val){var len=val.replace(/[\u4e00-\u9fa5]/g,"**").length;return val?len>=min^0?true:Lang('min').replace('{min}',min):true;},max:function(max,val){var len=val.replace(/[\u4e00-\u9fa5]/g,"**").length;return val?len<=max^0?true:Lang('max').replace('{max}',max):true;},pattern:function(pattern,val,item){if(pattern){try{pattern=eval(pattern);}catch(e){throw"The pattern error:"+pattern;}
return pattern.test(val)?true:item.attr('patterntips')||Lang('pattern');}
return true;}},Verify.fn={placeholder:function(input,item,title,self){var pos=input.eq(0).position(),place;place=$('<em class="ui-form-placeholder">'+title+'</em>').css({left:pos.left+self.opche.holderLeft,top:pos.top+self.opche.holderTop}).appendTo(item);place.click(function(){input.focus();});input.eq(0).bind('focus',function(){place[input.val()?'hide':'show']();}).bind('keyup',function(){place[input.val()?'hide':'show']();}).bind('blur',function(){if(!input.val()){place.show();}});setTimeout(function(){input.val()&&place.hide();},100);},autofocus:function(item){item.find(':input').focus();},ajaxurl:function(item){return item.attr('ajaxurl')||'';},parameter:function(item){return item.attr('parameter')||'';},focustips:function(){Verify.tips.apply(Verify,arguments)},errortips:function(){Verify.tips.apply(Verify,arguments)},successtips:false};return ZDK.procopy(Verify,ZDK.EventEmitter);});;function SetCookie(name,value){var argv=SetCookie.arguments;var argc=SetCookie.arguments.length;var expires=(argc>2)?argv[2]:null;var path=(argc>3)?argv[3]:null;var domain=(argc>4)?argv[4]:null;var secure=(argc>5)?argv[5]:false;document.cookie=name+"="+escape(value)
+((expires==null)?"":("; expires="+expires.toGMTString()))
+((path==null)?"":("; path="+path))
+((domain==null)?"":("; domain="+domain))
+((secure==true)?"; secure":"");}
function GetCookie(name){var arg=name+"=";var alen=arg.length;var clen=document.cookie.length;var i=0;while(i<clen){var j=i+alen;if(document.cookie.substring(i,j)==arg){return getCookieVal(j);}
i=document.cookie.indexOf(" ",i)+1;if(i==0)break;}
return null;}
function DeleteCookie(name){var exp=new Date();exp.setTime(exp.getTime()-1);var cval=0;document.cookie=name+"="+cval+"; expires="+exp.toGMTString();}
function getCookieVal(offset){var endstr=document.cookie.indexOf(";",offset);if(endstr==-1)endstr=document.cookie.length;return decodeURIComponent(document.cookie.substring(offset,endstr));}
function getUserImg(userid){if(!userid)return'http://t4.zbjimg.com/r/p/task/48.gif';var maxIUserid="000000000"+userid,sImgUrl;var iUserid=maxIUserid.substr(maxIUserid.length-9,9);sImgUrl='http://p6.zbjimg.com/user_avat_new/'+iUserid.substr(0,3)+'/'+iUserid.substr(3,2)+'/'+iUserid.substr(5,2)+'/48x48_avatar_'+iUserid.substr(7,2)+'.jpg';return sImgUrl;}
if(!window.ZDK){window.ZDK={};}
ZDK.cookie={getCookie:GetCookie,setCookie:SetCookie,deleteCookie:DeleteCookie,getUserImg:getUserImg};;ZDK.define('product.signup.login',function(require,exports){require('module.verify');require('org.cookie');if(GetCookie('loginyz')=="true"){$(".control-group:hidden").show();$("input[name=catcha]").parent().attr("required","true")}
var signup=$('#signup'),btn,un;verify=ZDK.module.verify({target:signup,button:(btn=signup.find('.butn')),errorClass:'error',successClass:'success',warningClass:'warning',holderLeft:10,holderTop:10});var refimg=verify.items.eq(2).parent();var refimage=refimg.find('img');var refhide=refimg.find('input[type=hidden]');var callref=function(){src="/login/verify?seed="+refhide.val()+"&t="+String(new Date().getTime());refimage.attr('src',src);refimg.find('input').not('[type=hidden]').val('');return false;};refimg.find('.refimg').click(callref);refimage.click(callref);verify.on('submitBefore',function(data){btn.removeClass('max-butn-orange').addClass('no-int').attr('disabled','disabled').html('<i></i>登录中...');$.ajax({url:signup.attr('action'),data:signup.serialize(),type:'post',dataType:'json',success:function(json){if(json.state==1){location.href=json.url;SetCookie('loginyz',"");var uns=verify.items.eq(0).find('input').val();var exp=new Date;exp.setTime(exp.getTime()+60*24*60*60*1000);document.cookie="_un="+uns+';expires='+exp.toGMTString();}else if(json.state==-5){var kid={},kurl=json.url;var win=ZDK.module.window({title:"系统提示",content:'<form id="verif-code" action="/login/mobileverify/verify-1"><p class="alert" style="margin-top:10px;">为了保护您的账户安全，请先进行手机验证。</p><div class="control-group clearfix"><label class="control-label" for="inputWarning" style="width:100px;padding-top:5px">手机验证码：</label><div required="" class="controls ui-form-item" data-index="0"><p><input type="text" data-type="number" style="width:100px;padding:5px" tabindex="1"><a href="" action-map="verif-code" style="text-decoration:underline; display:inline-block;margin:10px 0 0 15px"><i></i>获取验证码</a></p></div></div><p style="margin:0 0 10px 30px">验证短信将发送至：<strong class="code-num orange">'+json.num+'</strong></p></form>',id:'phoneAlert',width:400,mask:true,cache:false,zIndex:9000,close:false,hasIframe:true,cancel:false});win.on('onok',function(){$("#verif-code").submit();});$("#verif-code").submit(function(){$.ajax({url:"/login/mobileverify/verify-1",type:"post",data:kid+"&url="+kurl+"&code="+$("#verif-code").find("input[type='text']").val(),dataType:"json",success:function(json){if(json.state==1){window.location.href=kurl;return true;}else{ZDK.Error("错误提示",json.msg);}}});return false;})
win.on('oncancel',function(){errback();})
setTimeout(function(){$("#verif-code").find("a").click(function(){var _this=$(this);if(_this.attr("link-status")!="disabled"){$.ajax({url:"/login/mobileverify",type:"post",data:kid,dataType:"json",success:function(json){if(json.state==1){kid="kid="+json.kid;var _time=60;_this.css({color:"#999"}).attr("link-status","disabled");var time=setInterval(function(){_this.html(_time+"秒后重新发送验证码");_time--;if(_time<=0){clearInterval(time);_this.html("重发验证码").css({color:"#0B73BB"}).removeAttr("link-status");}},1000);}else{ZDK.Error("错误提示",json.msg);}}});}
return false;});},1000);}else{var target=verify.items.eq(parseInt(json.type)-1);$("#catchaimg").click();var input=target.find('input');ZDK.module.poptip({target:target,theme:'ui-verify-tips',content:'<p class="ui-warning-min">'+json.msg+'</p>',width:json.msg.length*16+45,cache:false});if(json.errcount>2){refimg.show();SetCookie('loginyz',true);$("input[name=catcha]").parent().attr("required","true")
verify=ZDK.module.verify({target:signup,button:btn,errorClass:'error',successClass:'success',warningClass:'warning',holderLeft:10,holderTop:10});verify.on('submitBefore',function(data){btn.removeClass('max-butn-orange').addClass('no-int').attr('disabled','disabled').html('<i></i>登录中...');$.ajax({url:signup.attr('action'),data:signup.serialize(),type:'post',dataType:'json',success:function(json){if(json.state==1){location.href=json.url;SetCookie('loginyz',"");var uns=verify.items.eq(0).find('input').val();var exp=new Date;exp.setTime(exp.getTime()+60*24*60*60*1000);document.cookie="_un="+uns+';expires='+exp.toGMTString();}else if(json.state==-5){var kid={},kurl=json.url;var win=ZDK.module.window({title:"系统提示",content:'<form id="verif-code" action="/login/mobileverify/verify-1"><p class="alert" style="margin-top:10px;">为了保护您的账户安全，请先进行手机验证。</p><div class="control-group clearfix"><label class="control-label" for="inputWarning" style="width:100px;padding-top:5px">手机验证码：</label><div required="" class="controls ui-form-item" data-index="0"><p><input type="text" data-type="number" style="width:100px;padding:5px" tabindex="1"><a href="" action-map="verif-code" style="text-decoration:underline; display:inline-block;margin:10px 0 0 15px"><i></i>获取验证码</a></p></div></div><p style="margin:0 0 10px 30px">验证短信将发送至：<strong class="code-num orange">'+json.num+'</strong></p></form>',id:'phoneAlert',width:400,mask:true,cache:false,zIndex:9000,close:false,hasIframe:true,cancel:false});win.on('onok',function(){$("#verif-code").submit();});$("#verif-code").submit(function(){$.ajax({url:"/login/mobileverify/verify-1",type:"post",data:kid+"&url="+kurl+"&code="+$("#verif-code").find("input[type='text']").val(),dataType:"json",success:function(json){if(json.state==1){window.location.href=kurl;return true;}else{ZDK.Error("错误提示",json.msg);}}});return false;})
win.on('oncancel',function(){errback();})
setTimeout(function(){$("#verif-code").find("a").click(function(){var _this=$(this);if(_this.attr("link-status")!="disabled"){$.ajax({url:"/login/mobileverify",type:"post",data:kid,dataType:"json",success:function(json){if(json.state==1){kid="kid="+json.kid;var _time=60;_this.css({color:"#999"}).attr("link-status","disabled");var time=setInterval(function(){_this.html(_time+"秒后重新发送验证码");_time--;if(_time<=0){clearInterval(time);_this.html("重发验证码").css({color:"#0B73BB"}).removeAttr("link-status");}},1000);}else{ZDK.Error("错误提示",json.msg);}}});}
return false;});},1000);}else{var target=verify.items.eq(parseInt(json.type)-1);$("#catchaimg").click();var input=target.find('input');ZDK.module.poptip({target:target,theme:'ui-verify-tips',content:'<p class="ui-warning-min">'+json.msg+'</p>',width:json.msg.length*16+45,cache:false});if(json.errcount>2){refimg.show();SetCookie('loginyz',true);$("input[name=catcha]").parent().attr("required","true")
verify=ZDK.module.verify({target:signup,button:btn,errorClass:'error',successClass:'success',warningClass:'warning',holderLeft:10,holderTop:10});}}
btn.addClass('max-butn-orange').removeClass('no-int').removeAttr('disabled').html('<i></i>登录');}});return false;}).on('itemfocus',function(data){var help=data.item.find('.help-inline');help.show();}).on('checkerror',function(data){var help=data.item.find('.help-inline');if(!help.attr('data-title')){help.attr('data-title',help.html());}
help.html(data.res);}).on('checksuccess',function(data){var help=data.item.find('.help-inline');if(!help.attr('data-title')){help.attr('data-title',help.html());}
help.html('');});}}
btn.addClass('max-butn-orange').removeClass('no-int').removeAttr('disabled').html('<i></i>登录');}});return false;}).on('itemfocus',function(data){var help=data.item.find('.help-inline');help.show();}).on('checkerror',function(data){var help=data.item.find('.help-inline');if(!help.attr('data-title')){help.attr('data-title',help.html());}
help.html(data.res);}).on('checksuccess',function(data){var help=data.item.find('.help-inline');if(!help.attr('data-title')){help.attr('data-title',help.html());}
help.html('');});function animate(wdn){if(wdn.data('ia')==1)return;wdn.data('ia',1);wdn.stop().animate({marginTop:-8},200,function(){wdn.stop().animate({marginTop:0},200,function(){wdn.data('ia',0)})})}
$('.other-login li').mouseenter(function(){animate($(this).find('a'));});if(un=document.cookie.match(/_un=([^;$]+)/)){var item=verify.items.eq(0).find('input').val(un[1]),close=$('<i></i>'),wrap=item.parent();wrap.addClass('ui-logined').append(close);close.click(function(){wrap.removeClass('ui-logined');close.remove();item.val('').focus();});item.bind('keyup',function(){if(item.val()!=un[1]){wrap.removeClass('ui-logined');close.remove();item.unbind(arguments.callee);}});}
$(".ui-logined i").length&&$(".ui-logined i").ie6hover()})